### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Driesboy** [basprohop/CombinedSlots#2]
[WARNING]: RuntimeException: "yaml_parse(): scanning error encountered during parsing: found unexpected ':' (line 11, column 26), context while scanning a plain scalar (line 11, column 11)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 148

**Comment by basprohop** [comment]
Post your config file please.

**Comment by Driesboy** [comment]
default file

**Comment by Driesboy** [comment]
nothing change

**Comment by Driesboy** [comment]
fixed remove [ ]
